CREATE OR REPLACE DATABASE CS_CHALLENGE_DB;

USE DATABASE CS_CHALLENGE_DB;

CREATE OR REPLACE SCHEMA CS_DATA;
CREATE OR REPLACE SCHEMA INTERNAL_STAGES;
CREATE OR REPLACE SCHEMA FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT CS_CHALLENGE_DB.FILE_FORMATS.CSV_FMT
    FIELD_DELIMITER = ','
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
;

CREATE OR REPLACE STAGE INTERNAL_STAGES.CS_EVENTS
    FILE_FORMAT = CS_CHALLENGE_DB.FILE_FORMATS.CSV_FMT
;

PUT 'file://./yds_data.csv' @INTERNAL_STAGES.CS_EVENTS;

CREATE OR REPLACE TABLE CS_DATA.GAMES(
    ID_IN_FILE NUMBER,
    MATCH_EVENT_ID NUMBER,
    LOCATION_X NUMBER,
    LOCATION_Y NUMBER,
    REMAINING_MIN NUMBER,
    POWER_OF_SHOT NUMBER,
    KNOCKOUT_MATCH NUMBER,
    GAME_SEASON VARCHAR(100),
    REMAINING_SEC NUMBER,
    DISTANCE_OF_SHOT NUMBER,
    IS_GOAL NUMBER,
    AREA_OF_SHOT VARCHAR(100),
    SHOT_BASICS VARCHAR(100),
    RANGE_OF_SHOT VARCHAR(100),
    TEAM_NAME VARCHAR(100),
    DATE_OF_GAME DATE,
    HOME_AWAY VARCHAR(100),
    SHOT_ID_NUMBER NUMBER,
    LAT_LNG VARCHAR(100),
    TYPE_OF_SHOT VARCHAR(100),
    TYPE_OF_COMBINED_SHOT VARCHAR(100),
    MATCH_ID NUMBER,
    TEAM_ID NUMBER,
    REMAINING_MIN_1 NUMBER,
    POWER_OF_SHOT_1 NUMBER,
    KNOCKOUT_MATCH_1 NUMBER,
    REMAINING_SEC_1 NUMBER,
    DISTANCE_OF_SHOT_1 NUMBER
);

COPY INTO CS_DATA.GAMES
    FROM @CS_CHALLENGE_DB.INTERNAL_STAGES.CS_EVENTS
    FILE_FORMAT = CS_CHALLENGE_DB.FILE_FORMATS.CSV_FMT
;

REMOVE @INTERNAL_STAGES.CS_EVENTS PATTERN='.*.csv.gz';

CREATE OR REPLACE TABLE CS_CHALLENGE_DB.CS_DATA.GAMES_SILVER (
    MATCH_ID	NUMBER(38,0),
    DATE_OF_GAME	DATE,
    YEAR_OF_GAME NUMBER(4,0),
    KNOCKOUT_MATCH	NUMBER(38,0),
    LAT_LNG	VARCHAR(100),
    HOME_AWAY	VARCHAR(100),
    LOCATION_X	NUMBER(38,0),
    LOCATION_Y	NUMBER(38,0),
    POWER_OF_SHOT	NUMBER(38,0),
    REMAINING_MIN	NUMBER(38,0),
    REMAINING_SEC	NUMBER(38,0),
    DISTANCE_OF_SHOT	NUMBER(38,0),
    IS_GOAL	NUMBER(38,0),
    AREA_OF_SHOT	VARCHAR(100),
    SHOT_BASICS	VARCHAR(100),
    RANGE_OF_SHOT	VARCHAR(100),
    TYPE_OF_SHOT	VARCHAR(100),
    TYPE_OF_COMBINED_SHOT	VARCHAR(100),
    NORMALIZED_TYPE_OF_SHOT	VARCHAR(100)
);

INSERT INTO CS_CHALLENGE_DB.CS_DATA.GAMES_SILVER (
    SELECT
        MATCH_ID,
        DATE_OF_GAME,
        YEAR(DATE_OF_GAME),
        KNOCKOUT_MATCH,
        LAT_LNG,
        HOME_AWAY,
        LOCATION_X,
        LOCATION_Y,
        POWER_OF_SHOT,
        REMAINING_MIN,
        REMAINING_SEC,
        DISTANCE_OF_SHOT,
        IS_GOAL,
        AREA_OF_SHOT,
        SHOT_BASICS,
        RANGE_OF_SHOT,
        TYPE_OF_SHOT,
        TYPE_OF_COMBINED_SHOT,
        COALESCE(TYPE_OF_SHOT, TYPE_OF_COMBINED_SHOT) NORMALIZED_TYPE_OF_SHOT
    FROM CS_CHALLENGE_DB.CS_DATA.GAMES
);